### ISSUE TITLE
Reconsider `validate` functions behaviour

### ISSUE THREAD

**Issue by roll** [frictionlessdata/implementations#13]
# Overview

See discussion- https://github.com/frictionlessdata/implementations/commit/a87f2c988f05c4cdcd72925dd459345e420c15f3

**Comment by pwalsh** [comment]
I'd like to hear what @amercader @akariv @vitorbaptista @brew think.

For me, we shouldn't standardise how exceptions are produced and consumed across different languages. We should follow the idioms of any language. 

Also, we shouldn't standardise just based on the same method/function name across different libraries - for example `validate` does not have to "mean" exactly the same thing in Table Schema and goodtables ( ref. https://github.com/frictionlessdata/goodtables-js/pull/17 ).

I applaud the efforts to have consistent interfaces across different libraries and even languages, but this definitely needs to take into consideration language idioms, and give way to them when it makes sense.

**Comment by roll** [comment]
@pwalsh 
I think that's confusion I didn't have in mind like cross-all-languages unification (esp. lang idioms related). I had some doubts how to incorporate `goodtables.validate` function but per https://github.com/frictionlessdata/goodtables-js/pull/17 and your comment on (1) it seems acceptable solution without changing other `validate` behavior. So I'm pretty happy to go this way.

I've created a revert PR - https://github.com/frictionlessdata/implementations/pull/14 - with `goodtables.validate` and clarification for individual language idioms usage.

**Comment by pwalsh** [comment]
@roll let's get some feedback from others first. I'm not coding daily so I think it is good to get feedback from some other team members :).

**Comment by vitorbaptista** [comment]
I agree on using the specific language construct. I doubt many people would use the implementations in more than one language, so it's more important to make each implementation feel "native" to its language, than to keep them consistent across languages.

A somewhat related topic on exceptions: make sure that the user is able to catch a single exception class to handle any exception thrown by our libraries (e.g. `RequestException` for `requests`). This means wrapping any exceptions thrown by our libraries' dependencies in our own exception classes (maybe just don't wrap base exceptions thrown by things like `open()`, but I don't have a strong opinion either way).

**Comment by roll** [comment]
I've reverted changes and added a preface pointing out that we use Python idioms by default - https://github.com/frictionlessdata/implementations#interface

Please re-open if further discussion is needed.
