### ISSUE TITLE
Review and provide feedback for PHP implementations

### ISSUE THREAD

**Issue by roll** [frictionlessdata/implementations#15]
# Overview

PHP implementations is mostly ready for review.

**Comment by roll** [comment]
DONE
https://github.com/frictionlessdata/datapackage-php/issues/18
https://github.com/frictionlessdata/datapackage-php/issues/19
https://github.com/frictionlessdata/datapackage-php/issues/20
https://github.com/frictionlessdata/tableschema-php/issues/25
https://github.com/frictionlessdata/tableschema-php/issues/26
https://github.com/frictionlessdata/tableschema-php/issues/27

**Comment by pwalsh** [comment]
thank you very much @roll !

**Comment by OriHoch** [comment]
thanks @roll  for your feedback

**Comment by roll** [comment]
thanks @OriHoch you're doing a great work!
