### ISSUE TITLE
Rebase dependent software on specs-v1

### ISSUE THREAD

**Issue by roll** [frictionlessdata/implementations#25]
# Overview

We've rebased `tableschema-py/js` and `datapackage-py/js` on specs-v1. There are some dependent software maintained by OKI that should be updated. This is meta issue to track the progress.

# Tasks

- [x] `goodtables-py`
- [x] `tableschema-<storage>` 
- [x] `tableschema.plugins`
- [x] `datapackage.load/save`
- [x] `goodtables.io`
- [x] `try.goodtables.io`
- [x] `goodtables-ui`
- [x] `os-packager`

**Comment by pwalsh** [comment]
WELL DONE!
