### ISSUE TITLE
Implement Frictionless Data specs v1 in core libs

### ISSUE THREAD

**Issue by pwalsh** [frictionlessdata/implementations#3]
# Description

No good having a spec with no implementation! We need to ensure coverage in the core libraries.

# Tasks

- [x] implement changes in Python/JavaScript
  - [x] tableschema-py
  - [x] datapackage-py
  - [x] tableschema-js
  - [x] datapackage-js
- [x] Open a v1 issue on each partner library, with a clear task list of what needs to be changed for v1 update - MOVED https://github.com/frictionlessdata/stack/issues/12

**Comment by roll** [comment]
DONE
(partner lib issue creation MOVED to https://github.com/frictionlessdata/stack/issues/12)
