### ISSUE TITLE
Apply defaults from JSON Schema specs

### ISSUE THREAD

**Issue by pwalsh** [frictionlessdata/implementations#4]
http://python-jsonschema.readthedocs.io/en/latest/faq/#why-doesn-t-my-schema-that-has-a-default-property-actually-set-the-default-on-my-instance

I've used defaults in the specs.

---

See also - https://github.com/frictionlessdata/datapackage-py/pull/138

---

# Tasks

- [x] apply defaults
  - [x] tableschema-py
  - [x] datapackage-py
  - [x] tableschema-js
  - [x] datapackage-js

**Comment by roll** [comment]
DONE
