### ISSUE TITLE
Start to publish next versions of jsontableschema as tableschema in package registries

### ISSUE THREAD

**Issue by roll** [frictionlessdata/implementations#5]
# Overview

Now we have our spec renamed - http://specs.frictionlessdata.io/table-schema/

**Comment by danfowler** [comment]
@roll 

- [ ] Update all descriptions with references to dataprotocols.org to instead point to specs.frictionlessdata.io equivalents (e.g. https://pypi.python.org/pypi/jsontableschema/0.9.0)

**Comment by roll** [comment]
SPLIT
- #8 
- https://github.com/frictionlessdata/jsontableschema-py/issues/148
- https://github.com/frictionlessdata/jsontableschema-js/issues/60
